pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    stages {
    stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('Checkout SCM') {
      steps {
        git branch: 'features/jenkinspipeline-stages2', url: 'https://github.com/Abbysola/ansible-config-mgt.git'
      }
    }

    stage('Prepare Ansible for Execution') {
      steps {
         sh 'echo ${WORKSPACE}'
         sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/depoy/ansible.cfg'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
         ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, 
         installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
      } 
    }  

    stage('Clean Workspace after build') {
      steps { 
          cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, 
          deleteDirs: true)
    
      }


    }
  }
}    
