---
- hosts: all
<<<<<<< HEAD
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

-  hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml
=======
<<<<<<< HEAD
- import_playbook: ../static-assignments/common-del.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml
=======
- import_playbook: ../static-assignments/common-del.yml
>>>>>>> 449cf366275bbf80daf8d29320df3a409b094b54
>>>>>>> b13a8a269410c97fdaf0092df25a585d453aa293
